[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18"]

[phases.install]
cmds = [
    "python3.11 -m pip install -r requirements.txt",
    "cd frontend && npm install && npm run build && cd .."
]

[start]
cmd = "python3.11 main_supabase.py"