[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs_20"]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt",
    "cd frontend && npm install && npm run build && cd .."
]

[start]
cmd = "/opt/venv/bin/python main_supabase.py"