# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
# Install Python dependencies
cmds = ["pip install -r requirements_supabase.txt"]

[phases.build]
# Build frontend
cmds = [
    "cd frontend && npm install",
    "cd frontend && npm run build",
    "cd .."
]

[start]
cmd = "python main_supabase.py"