[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install && npm run build && cd .."
]

[start]
cmd = "python main_supabase.py"